sudo: false
language: python
notifications:
  slack: nmgrl:ols00MOM4n3EimDpMiluJIyF
  email:
    on_failure: change

python:
  - 3.5

env:
  # Default values for common packages, override as needed
  global:
    - PYTHON=3.5

before_install:
  - export TZ=America/Denver
  # adapted from statsmodels travis file https://github.com/statsmodels/statsmodels/blob/master/.travis.yml
  # setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes --quiet conda
  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
#  - conda create --yes --quiet -n pychron-test ${PKGS} ${OPTIONAL}
  - conda create --yes --quiet -n pychron-test python=${PYTHON}
  - source activate pychron-test

  - conda install --yes statsmodels pyqt=4 PyYAML traits traitsui xlrd xlwt lxml apptools swig
  - pip install uncertainties codecov coverage chaco


script: coverage run setup.py test
after_success:
  - codecov